name: sambalam
description: HR management app for marking attendance, salary management, and employee management.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # State management
  provider: ^6.0.5
  get_it: ^7.6.0
  # Network and API
  dio: ^5.3.2
  http: ^1.2.2
  # Local storage
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI components
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_spinkit: ^5.2.0
  # Authentication
  local_auth: ^2.1.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  # Location and maps
  geolocator: ^10.0.0
  google_maps_flutter: ^2.4.0
  google_places_flutter: ^2.1.1 # For the Search Autocomplete UI
  location: ^5.0.0
  # Camera
  camera: ^0.10.5+2
  image_picker: ^1.0.2
  file_picker: ^8.1.2
  lucide_icons: ^0.257.0
  # Others
  intl: ^0.18.1
  url_launcher: ^6.2.1
  flutter_secure_storage: ^8.0.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.0
  device_info_plus: ^9.0.3
  package_info_plus: ^4.1.0
  table_calendar: ^3.0.9
  geocoding: ^4.0.0
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  syncfusion_flutter_xlsio: ^21.1.35
  path_provider: ^2.1.5
  gal: ^2.1.0
  open_file: ^3.3.2
  excel: ^4.0.0
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  mockito: ^5.4.2
  flutter_launcher_icons: ^0.13.1 # Keep this under dev_dependencies

# This must be at the ROOT level (no spaces before it)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic_launcher-web.png" 
  adaptive_icon_background: "#081c04" # Use your brand's dark green background
  adaptive_icon_foreground: "assets/images/ic_launcher-web.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/design.png
    - assets/images/logo.png
    - assets/images/logo2.png
    - assets/images/app_icon.png
    - assets/images/ic_launcher-web.png
    - assets/logo/
  fonts:
    - family: Sambalam
      fonts:
        # - asset: assets/fonts/Sambalam-Regular.ttf